GET http://localhost:5287/games/2


###
GET http://localhost:5287/games


### 
GET http://localhost:5287


###

POST http://localhost:5287/games
Content-Type: application/json

{
    "Name": "Game 5",
    "GenreId": "5", 
    "Price": 49.9,
    "releaseDate": "2026-09-29"
}


###

PUT  http://localhost:5287/games/1
Content-Type: application/json

{
    "Name": "Game 2",
    "GenreId": "2", 
    "Price": 20.9,
    "releaseDate": "2026-09-29"
}


### 
DELETE http://localhost:5287/games/3